
name: Sunday Sneaker Scrape v2

on:
  schedule:
    # At 02:00 UTC every Sunday
    - cron: '0 2 * * 0'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager firebase-admin

      - name: Run headless scraper
        run: python sneaker-scrapper.py

      - name: Prepare Firebase credentials
        # expose the secret as an env var
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo "Loaded service account into env var"

      - name: Upload scraped data to Firebase
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          python firebase_uploader.py

      - name: Upload JSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: sneakers-json
          path: sneakers_*.json
